# Decizie și Estimare în Prelucrarea Informației

## Introducere

### Organizare

- 4 credite
- Profesori
    - Curs: Nicolae Cleju
    - Laborator: Nicolae Cleju / Stefania Gall

- Orar
    - 14 cursuri (2h)
    - 14 laboratoare (2h)

- Ore de consultații: *To Be Announced*
    - cel mai bine prin programare prealabilă

### Notare

- Examen = 60%
    - 60% din nota finală
    - teorie și exerciții
    - Similar cu examenul de Information Theory (engl.)

- Laborator = 40%

    - Nota laborator = Quiz-uri săptămânale (+ eventuale teste anunțate)

- Nota finală = 60% Examen + 40% Aplicații


### Structura cursului
1. Capitolul I:   Semnale aleatoare
2. Capitolul II:  Elemente de teorie statistică a deciziei
3. Capitolul III: Estimarea statistică a parametrilor

### Bibliografie

1. Munteanu V. Detectie si estimare, Editura "Gh. Asachi" Iasi, 1997.
2. Borda M. E. Teoria transmisiunii informatiei, Partea I-a, Teoria informatiei si codarii (fundamente si aplicatii), Universitatea Tehnica Cluj - Napoca, 1993.
3. Munteanu, V., Teoria transmiterii informatiei, Editura "Gh. Asachi" Iasi, 2001.
4. Berlekamp, E. R. Algebraic Coding Theory. New-York: McGraw-Hill Book Company, 1968.
5. Brown, R. G., Hwang, P. Y. C., Intoduction to random signals and applied Kalman filtering, John Wiley and Sons, Inc., Second Edition, 1992.
6. Garcia, A. L., Probability and random processes for electrical engineering, Addison-Wesley Publishing Company, 1989

### Acces online

- pe github.com (https://github.com/nikcleju/DEPI)

- pe platforma Moodle (edu.etti.tuiasi.ro)
